CREATE OR REPLACE VIEW FINALQUERY1 AS 
--Get ingredients that appear in every condiment.
SELECT ING.MAINING
FROM XINGREDIENT ING
WHERE NOT EXISTS
    (SELECT CON.*
    FROM XCONDIMENT CON
    WHERE NOT EXISTS
        (SELECT CW.*
        FROM XCREATEDWITH CW
        WHERE CW.CONDNUM = CON.CONDNUM
        AND CW.INGNUM = ING.INGNUM));