CREATE OR REPLACE VIEW FINALQUERY2 AS 
--Get brands that only ship wasabi. 
SELECT BR.BRANDNAME
FROM XBRAND BR
WHERE BR.BRANDNUM NOT IN
    (SELECT MB.BRANDNUM
    FROM XMADEBY MB
    WHERE MB.CONDNUM NOT IN
        (SELECT CON.CONDNUM
        FROM XCONDIMENT CON
        WHERE CON.CONDNAME = 'Wasabi'));