CREATE OR REPLACE VIEW FINALQUERY8 AS 
--Get celebrity, sauce and condiment names of celebs 
--whose favorite condiment is in their favorite sauce.
SELECT CEL.CELEBNAME, SAU.SAUCENAME, CON.CONDNAME
FROM XCELEBRITY CEL, XCONDIMENT CON, XSAUCE SAU, XUSED USE
WHERE CEL.FAVCOND = CON.CONDNUM
AND CEL.FAVSAUCE = SAU.SAUCENUM
AND CON.CONDNUM = USE.CONDNUM
AND USE.SAUCENUM = SAU.SAUCENUM;