CREATE OR REPLACE VIEW TVJOINQUERY5 AS 
--Get all actor names and salaries along with producers if any.  
--Records: 160
SELECT P.PROD_NAME, PB.PROD_SALARY AS PRODSALARY, A.ACTOR_NAME, PL.ACTOR_SALARY AS ACTORSALARY 
FROM ZPRODBY PB RIGHT JOIN ZPLAY PL ON PB.PROD_SALARY = PL.ACTOR_SALARY 
RIGHT JOIN ZACTOR A ON A.ACTOR_NUM = PL.ACTOR_NUM 
LEFT JOIN ZPRODUCER P ON P.PROD_NUM = PB.PROD_NUM; 
