CREATE OR REPLACE VIEW TVJOINQUERY3 AS 
--Get all tv shows that have a spinoff. (List the name of both the original and the spinoff) 
--Records: 6
SELECT TVS.SHOW_NAME AS ORIGSHOW, TVSPIN.SHOW_NAME AS SPINOFF 
FROM ZTVSHOW TVS JOIN ZSPINOFF SPIN ON TVS.SHOW_NUM = SPIN.PARENT_NUM 
JOIN ZTVSHOW TVSPIN ON TVSPIN.SHOW_NUM = SPIN.SPINOFF_NUM; 
